<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AAML.Application/AAML.Application.csproj" />
    <ProjectReference Include="../AAML.Infrastructure.Common/AAML.Infrastructure.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AAML.Infrastructure.Linux.Tests" />
  </ItemGroup>
</Project>
